project_id = "qnavtvxemndvrutnavvm"

[functions.azure-login-initiate]
verify_jwt = false

[functions.azure-login-callback]
verify_jwt = false

[functions.office365-oauth-user-callback]
verify_jwt = false

[functions.office365-oauth-callback]
verify_jwt = false

[functions.public-google-maps-key]
verify_jwt = false

[functions.parse-modality-excel]
verify_jwt = true

[functions.get-shared-modality]
verify_jwt = false

[functions.send-reminder-now]
verify_jwt = true

[functions.ai-content-suggestions]
verify_jwt = true

[functions.sharepoint-browse-folders-cached]
verify_jwt = true

[functions.handle-incoming-email]
verify_jwt = false

[functions.fetch-mailchimp-campaign-content]
verify_jwt = true

[functions.gofax-send-fax]
verify_jwt = true

[functions.gofax-get-details]
verify_jwt = true

[functions.gofax-credit-balance]
verify_jwt = true
