project_id = "qnavtvxemndvrutnavvm"

[functions.azure-login-initiate]
verify_jwt = false

[functions.azure-login-callback]
verify_jwt = false

[functions.office365-oauth-user-callback]
verify_jwt = false

[functions.office365-oauth-callback]
verify_jwt = false
